# Generated by Django 5.0.6 on 2024-09-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_foodrecommendation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='nutritional_insights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
