# Generated by Django 5.0.6 on 2024-09-03 11:23

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_meal_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('ingredients', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='country_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.countrymeal'),
        ),
    ]
