# Generated by Django 5.0.6 on 2024-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_countrymeal_meal_country_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtype',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mealtype',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='countrymeal',
            name='is_ai_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countrymeal',
            name='times_selected',
            field=models.IntegerField(default=0),
        ),
    ]
