# Generated by Django 5.0.6 on 2024-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_mealtype_country_remove_mealtype_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='country_meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='Not Set', max_length=100),
            preserve_default=False,
        ),
    ]
