# Generated by Django 5.0.6 on 2024-09-03 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_meal_country_meal_meal_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_calorie_goal',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_carbs_goal',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_fat_goal',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_protein_goal',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.mealtype'),
        ),
        migrations.AddField(
            model_name='meal',
            name='nutritional_value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.nutritionalvalue'),
        ),
        migrations.CreateModel(
            name='HealthMetricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('blood_sugar', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
