# Generated by Django 5.0.6 on 2024-09-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecommendation',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
