# Generated by Django 5.0.6 on 2024-09-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_foodrecommendation_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='nutritional_insights',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='nutritional_value',
        ),
        migrations.AddField(
            model_name='nutritionalvalue',
            name='meal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_info', to='tracker.meal'),
            preserve_default=False,
        ),
    ]
