# Generated by Django 5.0.6 on 2024-09-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_remove_meal_meal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionalvalue',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.mealtype'),
        ),
        migrations.AddField(
            model_name='meal',
            name='nutritional_insights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='nutritional_value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_data', to='tracker.nutritionalvalue'),
        ),
    ]
